from pathlib import Path

import toml

root_dir = Path(__file__).resolve().parents[1]

with (root_dir / "pyproject.toml").open() as f:
    pyproject = toml.loads(f.read())

packages = [
    i["include"]
    for i in pyproject["tool"]["poetry"]["packages"]
    if "include" in i.keys()
]

for package in packages:
    with (root_dir / package / "__version__.py").open("w") as v:
        content = f"""# This file is automatically generated during the release process
# Do not edit manually
\"\"\"Version module for {package}.\"\"\"

__version__ = \"{pyproject["tool"]["poetry"]["version"]}\"
"""
        v.write(content)
