name: Publish Python package to Pypi

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    env:
      POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_PYPI_PASSWORD }}
      POETRY_HTTP_BASIC_PYPI_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_PYPI_USERNAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Install tools (Poetry)
        uses: Gr1N/setup-poetry@v8
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Install remaining CI/CD tools and dependencies
        run: poetry run inv cicd-setup.setup-test-stage
      - name: Publish to repository
        run: poetry run inv publish
