name: Publish Python package to Pypi

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    env:
      POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_PYPI_PASSWORD }}
      POETRY_HTTP_BASIC_PYPI_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_PYPI_USERNAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tools (Poetry)
        uses: Gr1N/setup-poetry@v8
      - name: Get full python version
        id: full-python-version
        shell: bash
        run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-publish-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-root
      - name: Install remaining CI/CD tools and dependencies
        run: poetry run inv setup-cicd-publish-stage
      - name: Publish to repository
        run: poetry run inv publish
